# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 13:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170510_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productquestion',
            options={'verbose_name_plural': 'Product Questions'},
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
