# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', s3direct.fields.S3DirectField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_images', to='portal.Product')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
    ]
